version: "3.9"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    env_file:
      - .env
    volumes:
      - ../..:/workspaces:cached    
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  db:
    image: mysql:latest
    restart: always
    volumes:
      - volume-db:/var/lib/mysql
    env_file:
      - .env
    networks:
      - csb

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    links:
      - db
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      PMA_ARBITRARY: 1
    networks:
      - csb

networks:
  csb:
    driver: bridge

volumes:
    volume-db: